[tool.poetry]
name = "ayon_api"
version = "0.1.9"
description = "Python api for AYON server"
authors = ["ynput.io <info@ynput.io>"]

[tool.poetry.dependencies]
requests = "^2.28.1"
six = "^1.15"
unidecode = "^1.3"
appdirs = { git = "https://github.com/ActiveState/appdirs.git", branch = "master" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"