[tool.poetry]
name = "ayon_api"
version = "0.1.16"
description = "Python api for AYON server"
authors = ["ynput.io <info@ynput.io>"]

[tool.poetry.dependencies]
requests = "^2.28.1"
six = "^1.15"
Unidecode = "^1.2"
appdirs = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"